

export const ContentActionTypes = {
    SET_LIFESTYLE_CONTENT_LIST: 'SET_LIFESTYLE_CONTENT_LIST',
    SET_MEMOIR_CONTENT_LIST: 'SET_MEMOIR_CONTENT_LIST',
    SET_POETRY_CONTENT_LIST: 'SET_POETRY_CONTENT_LIST',
    SET_EXCERPT_CONTENT_LIST: 'SET_EXCERPT_CONTENT_LIST'
}